name: Firebase Deploy  

on:
  push:
    branches:
      - main

jobs:
  use_firebase_project:
    name: Use Firebase project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2.3.2
      - name: Use Firebase project
        run: npx firebase-tools use --add ${{ secrets.FIREBASE_PROJECT_ID_DEV }} --token ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2.3.2
      - name: Install Dependencies
        run: npm install
        working-directory: client
      - name: Build
        env:
          CI: false        
        run: npm run build
        working-directory: client  
      - name: Archive Production Artifact
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: client/build

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2.3.2
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: build
          path: ./client/build
      - name: Deploy to Firebase Hosting
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting --token ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
        env:
          FIREBASE_TOKEN: --token ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
      - name: Install Dependencies for Functions
        run: npm install
        working-directory: functions
      - name: Build the Node.js server
        run: npm run build-server
        working-directory: functions
      - name: Deploy to Firebase Functions
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions --token ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
        env:
          FIREBASE_TOKEN: --token ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
          
